---
- name: Check that OS is Ubuntu or Debian
  ansible.builtin.assert:
    that:
      - ansible_distribution in ["Ubuntu", "Debian"]
    fail_msg: "This role supports only Ubuntu or Debian"
  tags: ["bootstrap"]

# Include other tasks
- name: Import package tasks
  ansible.builtin.import_tasks: packages.yml
  tags: ["bootstrap"]

- name: Import timezone tasks
  ansible.builtin.import_tasks: timezone.yml
  tags: ["bootstrap"]

- name: Import hostname tasks
  ansible.builtin.import_tasks: hostname.yml
  tags: ["bootstrap"]
